### PR TITLE
Failing test case for issue: words with commas after them are not found

### PR DESCRIPTION
**Pull request by tmcw**
Potentially this is the is-literal code being overeager?

### CODE REVIEW

**Comment by wooorm** [comment]
Ah, thanks for the test case!

It’s indeed [`is-literal`](https://github.com/wooorm/nlcst-is-literal/blob/39fd72d8171422893928d739a2a2e14025509d5f/index.js#L256). Rather a “feature” instead of a bug, albeit maybe a superfluous feature. The reasoning was in part due to the nature of awesome-syntax: something like `he - robust entity decoder` shouldn’t trigger. And I broadened it to include other punctuation too.

What real world example did you run in? Could you give some more context?

**Comment by tmcw** [comment]
Sure, so my usecase is the autolinker in our documentation. The text in question is:

https://www.mapbox.com/api-documentation/#styles

> Styles cannot be larger than 5MB. This limit only applies to the style document itself, not the sprites, fonts, tilesets, or other resources it references.

In this sentence, we want to link `tilesets` to a specific page, and use this not-quite-awesome chunk of code to do it: https://gist.github.com/tmcw/a993d269b1fe7efd253f The glossary looks like https://gist.github.com/tmcw/bee017c61529e2abc44e - `tileset` should be matched in the previous sentence.

**Comment by wooorm** [comment]
Ah, right. Everything relating to `nlcst-search` was written in quite a haste, so unfortunately the interface isn’t very beautiful (yet).

I’d say your problem is a valid use case. How about a solution similar to `allowApostrophe`? But then, probably, in an `options` object?

P.S. Also your hack to not allow matches inside other matches might be useful to internalise into `nlcst-search`.

**Comment by tmcw** [comment]
Yep, I think something like `allowCommas` would work great! Or would it be simpler to allow literals in general?

**Comment by wooorm** [comment]
Done! I added an `option` object which can be used as the fourth parameter. That object can have a `allowLiterals` property, which when given as `true`, includes literal phrases in the results.

Thanks for the failing test case. I’ll be releasing this in a minute, as `1.2.0`.

**Pull request closed without merging**
